spring.application.name=MyLibraryManagementPlatform

spring.datasource.url=jdbc:postgresql://localhost:5432/Z_MyLibraryManagementPlatformDB
spring.datasource.username=postgres
spring.datasource.password=Jumanji
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#----------------------------------Logging-----------------------------------------------------------------------
#debug=true
#trace=true

#Coloring the logs
spring.output.ansi.enabled=ALWAYS

#Writing logs to a file
#Commented to avoid large log file. Configuration working as expected.
#logging.file.name=errorAK.log

#Setting logging level of my custom package to DEBUG
#logging.level.com.RollNo8.MyLibraryManagementPlatform.service=DEBUG

#Defining a logging groups for classes. And then, setting logging level for that group
#logging.group.myServiceClasses = com.RollNo8.MyLibraryManagementPlatform.service.BooksService,com.RollNo8.MyLibraryManagementPlatform.service.AuthorsService
#logging.level.myServiceClasses=DEBUG

#---------------------------------Swagger Custom Path-------------------------------------------------------------
springdoc.swagger-ui.path=/dome

#Actuator base path
management.endpoints.web.base-path=/management
management.endpoints.web.exposure.include=*


#--------------------------------Actutator - Data to add in the information page---------------------------------
management.info.env.enabled=true
info.CreatedBy=  Roll No 8
info.version=v3






